### ISSUE TITLE
Slow downs (really slow mouse cursor for some seconds) and a crash

### ISSUE THREAD

**Issue by rcmcronny** [stijnvdb88/Snap.Net#1] opened 2020-04-13 14:34 UTC
Win10 19.09 works for me the UI, the player not, it shows no audio devices (i have 2 hdmi screens from which 1 use 1 for sound output)
Workaround:
It seems the "vcruntime140_1.dll" is missing, downloading this file and put it to the snapclient directory and the player works as it should :)
 
On the first use, the coursor slows down and suddenly the snapui disappears (crashed it seemed) after that there was a "missing dll (vccredist40.dll or so)" when i started the player, repair fixed it for now. The slowdown and crash happend as a played on 1 snapcast channel und changed the volume quickly from 100 -> 0 and back, but could not replicate it till now ^^
So far, good work !

**Comment by stijnvdb88** [comment] 2020-04-13 14:49
Thanks! This sounds like the issue akloeckner described (https://github.com/badaix/snapcast/issues/24#issuecomment-609024643) - I'll see if we can include those runtimes in the Snap.Net setup

**Comment by stijnvdb88** [comment] 2020-04-19 15:02
The missing VC runtime issue should now be fixed in latest release (https://github.com/stijnvdb88/Snap.Net/releases/tag/v0.19.0.2). 
As for the crash, I think https://github.com/stijnvdb88/Snap.Net/commit/82ca0b2d806d0a68de2da12d7a406600148c33ed fixed it (read: I haven't seen it again since pushing that commit).
I'll close this issue for now, but do let me know if you manage to reproduce that crash in 0.19.0.2 and I'll reopen it :)

**Closed by stijnvdb88** 2020-04-19 15:02 UTC
